data:
  train_dir: data/raw/training
  val_dir: data/raw/validation
  batch_size: 16
  image_size: 224
  num_workers: 2

model:
  num_classes: 10
  fc_params:
    linear_layer_out_features: 256
    dropout_rate: 0.4

training:
  epochs: 5
  lr: 0.001
  weight_decay: 0.0001
  device: cpu
  mlflow:
    url: "http://127.0.0.1:8080"
    experiment_name: "monkey_classifier"
    artifact_path: "model"
  plots:
    dir: plots/
    file_loss: plots/train_loss.png
    file_acc: plots/val_acc.png
    file_f1: plots/val_f1_macro.png
    metrics_path: plots/metrics.txt
  checkpoint_file: monkey_classifier.pth
  onnx_file: monkey_classifier.onnx
