data:
  train_dir: data/raw/training
  val_dir: data/raw/validation
  batch_size: 16
  image_size: 224
  num_workers: 2

model:
  num_classes: 10
  fc_params:
    linear_layer_out_features: 256
    dropout_rate: 0.4

training:
  epochs: 5
  lr: 0.001
  weight_decay: 0.0001
  device: cpu
